# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b5830ef0857b056c23608b0df3eedfca"
application_url = "https://edgecart-production.up.railway.app"
embedded = true
name = "EdgeCart"

[access_scopes]
scopes = "read_products,write_products,read_discounts"

[app_proxy]
url = "https://edgecart-production.up.railway.app"
subpath = "edge-cart"
prefix = "apps"

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [
  "https://edgecart-production.up.railway.app/auth/callback",
  "https://edgecart-production.up.railway.app/auth/shopify/callback",
  "https://edgecart-production.up.railway.app/api/auth"
]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true