name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"
[commands]
predev = "node scripts/setup-db.js && npm exec prisma generate"
dev = "npm exec prisma db push && npm exec react-router dev"
